# Generated by Django 4.0 on 2022-02-18 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_members_enrolmentnumber_alter_members_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='linkedIn',
            new_name='url',
        ),
    ]
