# Generated by Django 4.0 on 2022-02-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_linkedin_members_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='image',
            field=models.URLField(max_length=300),
        ),
    ]
