# Generated by Django 4.0 on 2022-02-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_members_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='image',
            field=models.URLField(max_length=300),
        ),
    ]
